# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cc9fa80ebe314bcf10f5c385677248fa75907e7c69d4ad014a4b1e1d0a926e7731904740878dd2eae9487522747468b5968bae8e167cadafe7e5b65c60b446d

test:
  secret_key_base: 72a989e77eea70c1f93bed40f1631571eddc377dc5edc4f7c5fe3e342c363bc214156518891ed86c139895f8cab1a1af5e4690c3932621baacde14919aafdebb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
